numpy

multi dimensional array

In [3]:
import numpy as np


In [4]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
lists_of_lists=[[1,2,3],[2,3,4],[4,5,6]]
np.array(lists_of_lists)

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.zeros(2,dtype=int)

array([0, 0])

In [11]:
np.zeros(2,int)

array([0, 0])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.ones((2,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [18]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
import numpy as np

In [22]:
np.random.rand(3,2)

array([[0.89312604, 0.83712732],
       [0.94459592, 0.21377678],
       [0.16880535, 0.56610685]])

In [24]:
np.random.randn(3,2)

array([[ 0.35977868, -1.61923683],
       [-0.23919136, -0.16168119],
       [-0.0117532 , -2.03424067]])

In [25]:
np.random.randint(44,100)

80

In [26]:
np.random.randint(20,56,100)

array([43, 47, 37, 39, 44, 27, 20, 41, 36, 28, 24, 38, 35, 22, 32, 55, 51,
       40, 51, 22, 39, 54, 55, 47, 38, 27, 48, 50, 34, 46, 22, 49, 22, 28,
       54, 40, 42, 40, 33, 32, 31, 28, 38, 49, 45, 46, 47, 45, 25, 34, 33,
       23, 33, 54, 25, 49, 36, 26, 34, 40, 26, 50, 32, 26, 31, 50, 30, 34,
       41, 36, 27, 52, 39, 41, 55, 28, 54, 36, 51, 48, 21, 23, 35, 26, 27,
       20, 53, 23, 29, 24, 38, 41, 42, 43, 47, 21, 25, 26, 39, 23])

In [27]:
sample_array=np.arange(30)

In [30]:
rand_array=np.random.randint(0,100,20)
rand_array

array([73, 53, 39, 41, 80, 84, 54, 89, 91, 31, 85, 94, 24, 44, 44, 16, 38,
       12,  4, 57])

In [28]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [73]:
sample_array.reshape(3,7)

ValueError: ignored

In [31]:
sample_array.reshape(4,7)

ValueError: ignored

In [33]:
rand_array.min()

4

In [34]:
rand_array.argmin()

18

In [35]:
rand_array.max()

94

In [36]:
rand_array.argmax()

11

In [ ]:
sample_array.dtype()

In [37]:
a=np.eye(5)

In [38]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
sample_array[-3]

18

In [41]:
sample_array[3:7]

array([13, 14, 15, 16])

In [42]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [47]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
sample_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [46]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [48]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

two-dimensional array

In [49]:
sample_matrix=np.array(([1,2,3,45],[23,45,45,45],[4,5,7,78],[4,56,7,67]))
sample_matrix

array([[ 1,  2,  3, 45],
       [23, 45, 45, 45],
       [ 4,  5,  7, 78],
       [ 4, 56,  7, 67]])

In [52]:
sample_matrix[2],[5]

(array([ 4,  5,  7, 78]), [5])

In [53]:
sample_matrix[3,:]

array([ 4, 56,  7, 67])

In [ ]:
sample_matrix[2]

In [55]:
sample_matrix[:,(3,2)]

array([[45,  3],
       [45, 45],
       [78,  7],
       [67,  7]])

selection techniques

In [56]:
sample_array=np.arange(1,20)

In [57]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [58]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [59]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [60]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [61]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [62]:
np.max(sample_array)

19

In [63]:
np.min(sample_array)

1

In [64]:
np.argmin(sample_array)

0

In [66]:
np.argmax(sample_array)

18

In [65]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [67]:
np.std(sample_array)

5.477225575051661

In [68]:
np.var(sample_array)

30.0

In [69]:
np.mean(sample_array)

10.0

In [70]:
array=np.random.randn(3,4)

In [71]:
np.round(array,decimals=1)

array([[ 0.2,  1.8,  2.1, -0.5],
       [ 0.3, -2. , -1.1,  1.4],
       [-1.9, -0.3,  1.7,  1.6]])

In [72]:
sports=np.array(['golf','cricket','fball','cricket','fball'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')